version: '3.8'

services:
  thebrain-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thebrain-mcp-server
    image: thebrain-mcp:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - THEBRAIN_API_KEY=${THEBRAIN_API_KEY}
      - THEBRAIN_CLIENT_ID=${THEBRAIN_CLIENT_ID}
      - THEBRAIN_CLIENT_SECRET=${THEBRAIN_CLIENT_SECRET}
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    stdin_open: true
    tty: true
    # Uncomment for HTTP transport
    # ports:
    #   - "3000:3000"
    # networks:
    #   - thebrain-net

# Uncomment for HTTP transport
# networks:
#   thebrain-net:
#     driver: bridge

# Example for development with hot reload
  # thebrain-mcp-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: thebrain-mcp-dev
  #   volumes:
  #     - ./src:/app/src
  #     - ./logs:/app/logs
  #   environment:
  #     - NODE_ENV=development
  #     - LOG_LEVEL=debug
  #   command: npm run dev
  #   stdin_open: true
  #   tty: true